// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL-0ZoXa5lfxor94zwafCdv13kswEEeJs',
    appId: '1:684747614293:web:5f8cff19a8292bf8faccdc',
    messagingSenderId: '684747614293',
    projectId: 'railway-crossing-alert-system',
    authDomain: 'railway-crossing-alert-system.firebaseapp.com',
    storageBucket: 'railway-crossing-alert-system.firebasestorage.app',
    measurementId: 'G-CNND67X3GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkJ5H_yfoX49sLsIRhzNxHCzEerh7l-k',
    appId: '1:684747614293:android:46190b1a87886b47faccdc',
    messagingSenderId: '684747614293',
    projectId: 'railway-crossing-alert-system',
    storageBucket: 'railway-crossing-alert-system.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl2Yge7aM7-s0Cp0BvzlEqwGQHAKudZCg',
    appId: '1:684747614293:ios:6bc359de4a3ae48ffaccdc',
    messagingSenderId: '684747614293',
    projectId: 'railway-crossing-alert-system',
    storageBucket: 'railway-crossing-alert-system.firebasestorage.app',
    iosBundleId: 'com.example.railwayCrossingAlertSystem',
  );
}
